version: '3'

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - backend/.env
    command: >
      sh -c "python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - media_volume:/backend/media
      - static_data:/backend/static
    expose:
      - 8000
    networks:
      - custom


  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    command: redis-server
    expose:
      - 6379
    networks:
      - custom

  celery:
    container_name: celery
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/backend
    depends_on:
      - redis
      - backend
    networks:
      - custom

  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - media_volume:/backend/media
      - static_data:/var/www/html/static
      - ./devops/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - redis
      - celery
    networks:
      - custom


networks:
  custom:
    driver: bridge

volumes:
  media_volume:
  static_data:
