version: '3'

services:
  db:
    container_name: db
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
      - backend/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - custom

  backend:
    container_name: backend
    image: backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - backend/.env
    command: >
      sh -c "python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - media_volume:/backend/media
      - static_data:/backend/static
    depends_on:
      - db
    expose:
      - 8000
    networks:
      - custom

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    command: redis-server
    expose:
      - 6379
    networks:
      - custom

  celery:
    container_name: celery
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/backend
    depends_on:
      - redis
      - backend
    networks:
      - custom

  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - media_volume:/backend/media
      - static_data:/backend/static
      - ./devops/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - backend
      - redis
      - celery
    networks:
      - custom


networks:
  custom:
    driver: bridge

volumes:
  db-data:
  media_volume:
  static_data:
