# Generated by Django 4.2.6 on 2024-02-01 13:24

from django.db import migrations, models
import file_server_app.models
import file_server_app.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        max_length=40,
                        upload_to=file_server_app.models.File.get_file_path,
                        validators=[file_server_app.validators.validate_file_extension],
                        verbose_name="Файл",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время загрузки")),
                ("processed", models.BooleanField(default=False, verbose_name="Обработан")),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
            },
        ),
    ]
